# Python for Economics and Finance
## Scientific Library
### 4 Pandas: 1 Introduction
### Shutao Cao
#### 2026-01-23

## Pandas Overview

Pandas is a library in Python that is used to manipulate and analyze heterogeneous data. By now, it is the standard Python tool for data manipulation.

Pandas provides two objects:

- [Series](https://pandas.pydata.org/docs/reference/api/pandas.Series.html): one-dimensional labeled array of any data type, integers, strings, Python objects etc.

- [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame): a two-dimensional tabular data structure like a table with rows and columns. It is inspired by dataframe in R.

For (very) large data set (think of data with at least 1 billion rows or columns), one should use [https://dask.org](Dask), which we do not learn in this course.

Main features of pandas include
- data file input and output
- data wrangling: reshaping, slicing, aggregation, merging and joining, grouping etc.
- time series data: aggregation, etc.
- plotting

To use pandas, we need to import it. In using pandas, we often use Numpy modules.

The names np for numpy and pd for pandas are popular, so should be followed.

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'2.3.3'

Built-in documentation. Typing ? can display information of a class or method.

Typing the Tab key shows all available methods or classes.

In [2]:
# Uncomment the line below to show manual for pd.Series
# pd.Series?

In [3]:
# Uncomment the line below and hit the Tab key after the dot.
# pd.

## Series

We can create series from Python list, tuple, dictionary, or Numpy arrays. We can also load data from file and crate series.

In [4]:
x = [9,8,7,6,-1]
y = ('a','b','c','d','e')
datax = pd.Series(x)
datay = pd.Series(y)

In [5]:
datax

0    9
1    8
2    7
3    6
4   -1
dtype: int64

In [6]:
datay

0    a
1    b
2    c
3    d
4    e
dtype: object

In [7]:
z = dict(zip(y,x))
print('z =',z)
dataz = pd.Series(data=z)
dataz

z = {'a': 9, 'b': 8, 'c': 7, 'd': 6, 'e': -1}

a    9
b    8
c    7
d    6
e   -1
dtype: int64

Data can be accessed by index objects or by position or boolean operator.
- `.loc[]` uses index
- `.iloc[]` uses the position of data

In [8]:
dataz.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [9]:
dataz.loc['c']

np.int64(7)

In [10]:
dataz.loc['c':'e']

c    7
d    6
e   -1
dtype: int64

In [11]:
dataz.iloc[2]

np.int64(7)

In [12]:
dataz.iloc[2:]

c    7
d    6
e   -1
dtype: int64

In [13]:
d = dataz[dataz<8]
d

c    7
d    6
e   -1
dtype: int64

In [14]:
# create series from numpy array
x = np.array(x)
datax = pd.Series(x)
datax

0    9
1    8
2    7
3    6
4   -1
dtype: int64

We can define the index.

In [15]:
x = np.array(x)
datax = pd.Series(x, index=y)
datax

a    9
b    8
c    7
d    6
e   -1
dtype: int64

Reset the index, if we need to.

In [16]:
datax.index=['f','g','h','i','j']
datax

f    9
g    8
h    7
i    6
j   -1
dtype: int64

Sorting Series by index or by value

In [17]:
dataz.sort_index(ascending=True)

a    9
b    8
c    7
d    6
e   -1
dtype: int64

In [18]:
dataz.sort_values(ascending=True)

e   -1
d    6
c    7
b    8
a    9
dtype: int64

There are more operations on Series. They are similar to operations on Numpy arrays. For example, .add(), .product(), .cumsum(), .max(), .argmax(), .median() etc.

## DataFrame
The DataFrame object is a 2-dimensional labeled data structure with columns of potentially different types. We think of it like a spreadsheet table.

- A DataFrame can be created from:
    - Dict of 1D ndarrays, lists, dicts, or Series
    - 2-D numpy array
    - A list of dictionaries
    - Another Dataframe

Syntax:

``` python
df = pd.DataFrame(data, index = index, columns = columns)
```
- ```index```/ ``` columns ``` is a list of the row / column labels.

See [**pandas.DataFrame**](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) for a complete list of methods and classes on DataFrame.

#### DataFrame Creation 
Create data frame from dict of series or dictionaries:
- The index of the resulting DataFrame will be the union of the indices of the various Series. If there are any nested dictionaries, these will be first converted to Series.
- If no columns are passed, the columns will be the sorted list of dict keys.

In [19]:
population_dict = {'California': 39538223, 'Texas': 29145505,
                   'Florida': 21538187, 'New York': 20201249,
                   'Pennsylvania': 13002700}
population = pd.Series(population_dict)
population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

In [20]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312, 
             'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [21]:
states = pd.DataFrame({'population': population, 'area': area})
states

              population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [22]:
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='object')

In [23]:
states.columns

Index(['population', 'area'], dtype='object')

In [24]:
states.loc[:,'area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

Data frame can be constructed from series. 

In the above, we created a Series `population`, we make a data frame from it.

In [25]:
pd.DataFrame(population, columns=['population'])

              population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

Create data frame from a list of dictionaries:

In [26]:
data_dict = [{'a': i, 'b': 2 * i} for i in range(3)]
datax = pd.DataFrame(data_dict)
datax

   a  b
0  0  0
1  1  2
2  2  4

Create data frame from Numpy arrays

In [27]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'],index=['a', 'b', 'c'])

        foo       bar
a  0.058828  0.817508
b  0.587033  0.679317
c  0.416907  0.014989

In [49]:
# Example: use pandas to create time series
import pandas as pd
np.random.seed(1234)
data = np.random.randn(10, 2)  # 5x2 matrix of N(0, 1) random draws
dates = pd.date_range(start='12/28/2010', periods=10, freq='W')
df = pd.DataFrame(data, columns=('price', 'weight'), index=dates)
print(df)

               price    weight
2011-01-02  0.471435 -1.190976
2011-01-09  1.432707 -0.312652
2011-01-16 -0.720589  0.887163
2011-01-23  0.859588 -0.636524
2011-01-30  0.015696 -2.242685
2011-02-06  1.150036  0.991946
2011-02-13  0.953324 -2.021255
2011-02-20 -0.334077  0.002118
2011-02-27  0.405453  0.289092
2011-03-06  1.321158 -1.546906

In [29]:
df.mean()

price     0.555473
weight   -0.578068
dtype: float64

### Create DataFrame from files
Pandas can read in data from:
- Comma Separated Values (CSV) files
- MS Excel files
- Data files created in Stata, SAS, SQL, etc.

In [30]:
# !cat tbl14100287_wide.csv

In [50]:
# Example: read monthly Canadian labor market condition data in CSV form
import pandas as pd
cansimid = '14100287'
#filename = 'tbl14100287_wide.csv'
filename = 'tbl14100287Final3.csv'
lfs = pd.read_csv(filename, index_col=0)

In [51]:
# Convert the index to time series
lfs.index = pd.to_datetime(lfs.index)

In [52]:
lfs.index

DatetimeIndex(['1976-01-01', '1976-02-01', '1976-03-01', '1976-04-01',
               '1976-05-01', '1976-06-01', '1976-07-01', '1976-08-01',
               '1976-09-01', '1976-10-01',
               ...
               '2025-03-01', '2025-04-01', '2025-05-01', '2025-06-01',
               '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01',
               '2025-11-01', '2025-12-01'],
              dtype='datetime64[ns]', name='ref_date', length=600, freq=None)

In [53]:
lfs.columns

Index(['emplBothSex', 'emplFemale', 'emplFullBothSex', 'emplFullFemale',
       'emplFullMale', 'emplMale', 'emplPartBothSex', 'emplPartFemale',
       'emplPartMale', 'emplRateBothSex', 'emplRateFemale', 'emplRateMale',
       'labForceBothSex', 'labForceFemale', 'labForceMale',
       'participRateBothSex', 'participRateFemale', 'participRateMale',
       'populationBothSex', 'populationFemale', 'populationMale',
       'unemplBothSex', 'unemplFemale', 'unemplMale', 'unemplRateBothSex',
       'unemplRateFemale', 'unemplRateMale'],
      dtype='object')

Convert the monthly employment data to be quarterly:

In [54]:
lfsQtr = lfs.resample('QS-OCT').mean()
lfsQtr = lfsQtr.round(2)
lfsQtr

,emplBothSex,emplFemale,emplFullBothSex,emplFullFemale,emplFullMale,emplMale,emplPartBothSex,emplPartFemale,emplPartMale,emplRateBothSex,...,participRateMale,populationBothSex,populationFemale,populationMale,unemplBothSex,unemplFemale,unemplMale,unemplRateBothSex,unemplRateFemale,unemplRateMale
ref_date,,,,,,,,,,,,,,,,,,,,,
1976-01-01,9666.90,3566.33,8469.30,2735.10,5734.20,6100.53,1197.57,831.23,366.30,57.23,...,77.93,16891.70,8538.53,8353.20,718.17,307.77,410.40,6.93,7.93,6.30
1976-04-01,9737.53,3604.93,8529.63,2756.80,5772.83,6132.60,1207.87,848.10,359.73,57.27,...,77.73,17008.10,8599.70,8408.40,718.13,312.23,405.90,6.87,7.97,6.20
1976-07-01,9778.40,3635.07,8562.97,2779.30,5783.70,6143.37,1215.43,855.83,359.67,57.10,...,77.53,17121.43,8659.10,8462.33,753.40,336.07,417.33,7.17,8.43,6.37
1976-10-01,9824.70,3673.90,8568.27,2790.33,5777.90,6150.80,1256.43,883.60,372.87,57.07,...,77.53,17210.97,8705.67,8505.33,785.97,338.47,447.50,7.43,8.43,6.77
1977-01-01,9869.73,3700.57,8605.30,2810.80,5794.50,6169.17,1264.43,889.73,374.67,57.03,...,77.70,17300.70,8752.77,8548.00,829.93,358.83,471.10,7.77,8.83,7.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-01,20842.13,9834.73,17093.67,7497.03,9596.63,11007.37,3748.43,2337.70,1410.77,60.90,...,69.60,34224.67,17202.00,17022.63,1507.47,666.60,840.87,6.73,6.33,7.13
2025-01-01,20983.27,9906.50,17152.10,7503.07,9649.07,11076.80,3831.20,2403.40,1427.77,61.03,...,69.53,34389.67,17283.83,17105.83,1490.70,669.07,821.60,6.63,6.33,6.90
2025-04-01,21002.87,9902.60,17178.67,7529.10,9649.53,11100.30,3824.23,2373.47,1450.73,60.83,...,69.63,34533.80,17357.13,17176.67,1558.40,696.13,862.23,6.93,6.57,7.20
2025-07-01,20996.87,9912.17,17187.27,7550.20,9637.07,11084.70,3809.60,2361.97,1447.63,60.60,...,69.50,34643.63,17414.93,17228.70,1587.10,693.50,893.60,7.03,6.53,7.47
2025-10-01,21120.37,9966.80,17247.97,7590.90,9657.07,11153.57,3872.40,2375.90,1496.50,60.87,...,69.43,34710.50,17451.40,17259.07,1528.60,696.67,832.00,6.73,6.53,6.93

Pandas can write data frames to files of format csv, excel, etc.

In the example below, lfsQtr is saved to the folder that holds the current .ipynb notebook.

We can specify the folder name to save lfsQtr to a designated folder.

In [55]:
lfsQtr.to_csv('lfsQtr.csv')

We can also compress the csv file, useful if data size is large.

In [56]:
compression_opts = dict(method='zip', archive_name='lfsQtr.csv')  
lfsQtr.to_csv('lfsQtr.csv.zip', index=True,compression=compression_opts)

### Data Indexing and Selection
Two methods of indexing:
- The .loc[] attribute: indexing and slicing that references the explicit index (index labels)
- The .iloc[] attribute: indexing and slicing that references the implicit Python-style index, thus it is an indexing with integers.

Ways of slicing using .iloc are similar to those for Numpy arrays, Python lists and strings.

In [57]:
states

              population    area     density party
California      39538223  423967   93.257784     D
Texas           29145505  695662   41.896072     R
Florida         21538187  170312  126.463121     R
New York        20201249  141297  142.970120     D
Pennsylvania    13002700  119280  109.009893     D

In [58]:
states['California':'New York']

            population    area     density party
California    39538223  423967   93.257784     D
Texas         29145505  695662   41.896072     R
Florida       21538187  170312  126.463121     R
New York      20201249  141297  142.970120     D

In [59]:
states.loc['California':'New York']

            population    area     density party
California    39538223  423967   93.257784     D
Texas         29145505  695662   41.896072     R
Florida       21538187  170312  126.463121     R
New York      20201249  141297  142.970120     D

In [60]:
states.loc[['California','Florida'], ['area', 'population']]

              area  population
California  423967    39538223
Florida     170312    21538187

In [61]:
states.iloc[[0,2]]

            population    area     density party
California    39538223  423967   93.257784     D
Florida       21538187  170312  126.463121     R

In [62]:
states.iloc[:-2]

            population    area     density party
California    39538223  423967   93.257784     D
Texas         29145505  695662   41.896072     R
Florida       21538187  170312  126.463121     R

Create a column

In [63]:
states['density'] = states['population']/states['area']
states.head()

              population    area     density party
California      39538223  423967   93.257784     D
Texas           29145505  695662   41.896072     R
Florida         21538187  170312  126.463121     R
New York        20201249  141297  142.970120     D
Pennsylvania    13002700  119280  109.009893     D

Selection with explicit rules

In [64]:
states.loc[states.density > 100, ['population', 'density']]

              population     density
Florida         21538187  126.463121
New York        20201249  142.970120
Pennsylvania    13002700  109.009893

Modify values

In [65]:
states['party']='D'
states

              population    area     density party
California      39538223  423967   93.257784     D
Texas           29145505  695662   41.896072     D
Florida         21538187  170312  126.463121     D
New York        20201249  141297  142.970120     D
Pennsylvania    13002700  119280  109.009893     D

In [66]:
states.loc[['Texas','Florida'],['party']]='R'
states

              population    area     density party
California      39538223  423967   93.257784     D
Texas           29145505  695662   41.896072     R
Florida         21538187  170312  126.463121     R
New York        20201249  141297  142.970120     D
Pennsylvania    13002700  119280  109.009893     D

In [67]:
lfsQtr.loc['2019-01-01':'2020-04-01',['unemplRateBothSex']]

            unemplRateBothSex
ref_date
2019-01-01               5.77
2019-04-01               5.60
2019-07-01               5.67
2019-10-01               5.70
2020-01-01               6.60
2020-04-01              13.50

In [68]:
lfsQtr.loc['2018-01-01':,['unemplRateBothSex']]

            unemplRateBothSex
ref_date
2018-01-01               5.90
2018-04-01               5.90
2018-07-01               5.90
2018-10-01               5.63
2019-01-01               5.77
2019-04-01               5.60
2019-07-01               5.67
2019-10-01               5.70
2020-01-01               6.60
2020-04-01              13.50
2020-07-01              10.03
2020-10-01               8.83
2021-01-01               8.47
2021-04-01               8.13
2021-07-01               7.17
2021-10-01               6.17
2022-01-01               5.77
2022-04-01               5.17
2022-07-01               5.03
2022-10-01               5.03
2023-01-01               5.07
2023-04-01               5.23
2023-07-01               5.50
2023-10-01               5.73
2024-01-01               5.90
2024-04-01               6.30
2024-07-01               6.57
2024-10-01               6.73
2025-01-01               6.63
2025-04-01               6.93
2025-07-01               7.03
2025-10-01               6.73