# Python for Economics and Finance
## Scientific Library
### 4 Pandas: 2 Data Processing
### Shutao Cao
#### 2026-01-30

In [1]:
import numpy as np
import pandas as pd
pd.__version__
pd.set_option("mode.copy_on_write", True)

## Data Cleaning and Preparation
We use the data on labor market condition as an example. I've cleaned up the data. Later on I will show how to process the labor market data from its raw form.

In [7]:
# Example: read monthly Canadian labor market condition data in CSV form
cansimid = '14100287'
filename = 'tbl14100287Final3.csv'
#lfs = pd.read_csv(filename, index_col=0)
lfs = pd.read_csv(filename)
lfs.columns

Index(['ref_date', 'emplBothSex', 'emplFemale', 'emplFullBothSex',
       'emplFullFemale', 'emplFullMale', 'emplMale', 'emplPartBothSex',
       'emplPartFemale', 'emplPartMale', 'emplRateBothSex', 'emplRateFemale',
       'emplRateMale', 'labForceBothSex', 'labForceFemale', 'labForceMale',
       'participRateBothSex', 'participRateFemale', 'participRateMale',
       'populationBothSex', 'populationFemale', 'populationMale',
       'unemplBothSex', 'unemplFemale', 'unemplMale', 'unemplRateBothSex',
       'unemplRateFemale', 'unemplRateMale'],
      dtype='object')

In [8]:
lfs.head(10)

,ref_date,emplBothSex,emplFemale,emplFullBothSex,emplFullFemale,emplFullMale,emplMale,emplPartBothSex,emplPartFemale,emplPartMale,...,participRateMale,populationBothSex,populationFemale,populationMale,unemplBothSex,unemplFemale,unemplMale,unemplRateBothSex,unemplRateFemale,unemplRateMale
0,1976-01,9636.7,3551.3,8431.0,2718.9,5712.1,6085.3,1205.6,832.4,373.2,...,78.0,16852.4,8517.7,8334.7,733.0,314.0,419.0,7.1,8.1,6.4
1,1976-02,9659.8,3562.8,8467.5,2735.4,5732.0,6097.0,1192.3,827.4,364.9,...,78.0,16892.0,8538.8,8353.3,730.0,313.8,416.2,7.0,8.1,6.4
2,1976-03,9704.2,3584.9,8509.4,2751.0,5758.5,6119.3,1194.8,833.9,360.8,...,77.8,16930.7,8559.1,8371.6,691.5,295.5,396.0,6.7,7.6,6.1
3,1976-04,9738.2,3592.9,8540.1,2752.4,5787.6,6145.3,1198.1,840.4,357.6,...,78.0,16969.4,8579.4,8390.0,713.1,311.1,402.0,6.8,8.0,6.1
4,1976-05,9726.1,3600.3,8529.6,2759.3,5770.4,6125.8,1196.4,841.0,355.4,...,77.6,17008.1,8599.7,8408.4,720.0,317.8,402.2,6.9,8.1,6.2
5,1976-06,9748.3,3621.6,8519.2,2758.7,5760.5,6126.7,1229.1,862.9,366.2,...,77.6,17046.8,8620.0,8426.8,721.3,307.8,413.5,6.9,7.8,6.3
6,1976-07,9759.5,3619.8,8544.4,2764.7,5779.7,6139.8,1215.1,855.1,360.1,...,77.9,17085.5,8640.3,8445.2,779.9,338.0,441.9,7.4,8.5,6.7
7,1976-08,9780.5,3644.3,8561.9,2785.6,5776.4,6136.2,1218.6,858.8,359.8,...,77.4,17124.4,8660.7,8463.7,743.6,332.0,411.6,7.1,8.3,6.3
8,1976-09,9795.2,3641.1,8582.6,2787.6,5795.0,6154.1,1212.6,853.6,359.1,...,77.3,17154.4,8676.3,8478.1,736.7,338.2,398.5,7.0,8.5,6.1
9,1976-10,9782.5,3655.5,8537.7,2779.9,5757.8,6127.0,1244.8,875.7,369.2,...,77.4,17183.4,8691.3,8492.1,782.6,332.6,450.0,7.4,8.3,6.8

### Missing values
The data have no missing, I'll create some.

Pandas uses the floating-point value NaN (Not a Number) to represent missing data.

In [9]:
lfs.loc[lfs['emplPartBothSex']<1500,'emplPartBothSex']=np.nan

In [10]:
lfs.head(100)

,ref_date,emplBothSex,emplFemale,emplFullBothSex,emplFullFemale,emplFullMale,emplMale,emplPartBothSex,emplPartFemale,emplPartMale,...,participRateMale,populationBothSex,populationFemale,populationMale,unemplBothSex,unemplFemale,unemplMale,unemplRateBothSex,unemplRateFemale,unemplRateMale
0,1976-01,9636.7,3551.3,8431.0,2718.9,5712.1,6085.3,NaN,832.4,373.2,...,78.0,16852.4,8517.7,8334.7,733.0,314.0,419.0,7.1,8.1,6.4
1,1976-02,9659.8,3562.8,8467.5,2735.4,5732.0,6097.0,NaN,827.4,364.9,...,78.0,16892.0,8538.8,8353.3,730.0,313.8,416.2,7.0,8.1,6.4
2,1976-03,9704.2,3584.9,8509.4,2751.0,5758.5,6119.3,NaN,833.9,360.8,...,77.8,16930.7,8559.1,8371.6,691.5,295.5,396.0,6.7,7.6,6.1
3,1976-04,9738.2,3592.9,8540.1,2752.4,5787.6,6145.3,NaN,840.4,357.6,...,78.0,16969.4,8579.4,8390.0,713.1,311.1,402.0,6.8,8.0,6.1
4,1976-05,9726.1,3600.3,8529.6,2759.3,5770.4,6125.8,NaN,841.0,355.4,...,77.6,17008.1,8599.7,8408.4,720.0,317.8,402.2,6.9,8.1,6.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1983-12,11187.4,4692.8,9289.7,3377.4,5912.3,6494.7,1897.8,1315.4,582.4,...,76.6,19462.2,9887.5,9574.7,1429.1,585.3,843.8,11.3,11.1,11.5
96,1984-01,11168.6,4680.9,9297.8,3389.4,5908.4,6487.7,1870.8,1291.5,579.3,...,76.4,19483.7,9898.7,9585.0,1423.3,586.9,836.3,11.3,11.1,11.4
97,1984-02,11203.9,4699.2,9325.8,3398.7,5927.1,6504.7,1878.1,1300.4,577.7,...,76.4,19506.2,9910.4,9595.8,1425.4,596.2,829.2,11.3,11.3,11.3
98,1984-03,11205.9,4705.3,9341.0,3417.5,5923.5,6500.6,1864.9,1287.8,577.1,...,76.4,19524.2,9919.7,9604.5,1424.7,589.1,835.6,11.3,11.1,11.4
99,1984-04,11198.5,4700.5,9331.1,3412.2,5918.9,6498.0,1867.4,1288.3,579.1,...,76.5,19546.8,9931.6,9615.3,1456.0,599.1,856.8,11.5,11.3,11.6

Methods of handling missing values

|Method	| Description |
|-------|-------------|
| dropna | Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.|
| fillna | Fill in missing data with some value or using an interpolation method such as "ffill" or "bfill".|
| isna | Return Boolean values indicating which values are missing/NA.|
| notna | Negation of isna, returns True for non-NA values and False for NA values.|

**Important**: These methods return new objects, and do not modify the content of original object.

In [11]:
# Delete rows with missing values
lfs2 = lfs.loc[:,['ref_date','emplMale','emplPartBothSex','emplPartFemale']]
lfs2.dropna(how="all") # is a new object, but lfs2 is unmodified.
lfs2.head(20)

   ref_date  emplMale  emplPartBothSex  emplPartFemale
0   1976-01    6085.3              NaN           832.4
1   1976-02    6097.0              NaN           827.4
2   1976-03    6119.3              NaN           833.9
3   1976-04    6145.3              NaN           840.4
4   1976-05    6125.8              NaN           841.0
5   1976-06    6126.7              NaN           862.9
6   1976-07    6139.8              NaN           855.1
7   1976-08    6136.2              NaN           858.8
8   1976-09    6154.1              NaN           853.6
9   1976-10    6127.0              NaN           875.7
10  1976-11    6154.8              NaN           890.3
11  1976-12    6170.6              NaN           884.8
12  1977-01    6172.7              NaN           887.1
13  1977-02    6172.0              NaN           891.2
14  1977-03    6162.8              NaN           890.9
15  1977-04    6182.4              NaN           885.3
16  1977-05    6179.9              NaN           905.1
17  1977-06    6179.2              NaN           906.1
18  1977-07    6182.4              NaN           910.1
19  1977-08    6198.9              NaN           912.3

In [12]:
lfs3 = lfs2.dropna()
lfs3.head(10)

   ref_date  emplMale  emplPartBothSex  emplPartFemale
44  1979-09    6577.5           1509.7          1059.6
45  1979-10    6587.9           1512.4          1075.6
46  1979-11    6602.0           1518.5          1079.1
47  1979-12    6608.9           1519.1          1074.6
48  1980-01    6609.8           1522.1          1087.5
49  1980-02    6631.4           1527.6          1073.3
50  1980-03    6606.4           1539.3          1091.8
51  1980-04    6610.6           1558.3          1109.6
52  1980-05    6581.2           1540.6          1103.1
53  1980-06    6605.7           1556.9          1111.7

In [13]:
# if delete columns with missing values, do:
lfs3=lfs2.dropna(axis=1)
lfs3.head()

  ref_date  emplMale  emplPartFemale
0  1976-01    6085.3           832.4
1  1976-02    6097.0           827.4
2  1976-03    6119.3           833.9
3  1976-04    6145.3           840.4
4  1976-05    6125.8           841.0

Fill in missing values with any thing you choose

In [14]:
lfs3=lfs2.fillna(-1.0)
lfs3.head()

  ref_date  emplMale  emplPartBothSex  emplPartFemale
0  1976-01    6085.3             -1.0           832.4
1  1976-02    6097.0             -1.0           827.4
2  1976-03    6119.3             -1.0           833.9
3  1976-04    6145.3             -1.0           840.4
4  1976-05    6125.8             -1.0           841.0

In [15]:
## Can also use replace method
lfs3=lfs2.replace(np.nan, -2)
lfs3.head()

  ref_date  emplMale  emplPartBothSex  emplPartFemale
0  1976-01    6085.3             -2.0           832.4
1  1976-02    6097.0             -2.0           827.4
2  1976-03    6119.3             -2.0           833.9
3  1976-04    6145.3             -2.0           840.4
4  1976-05    6125.8             -2.0           841.0

### Duplicated data
For this purpose, I insert a row that is identical to the row 1976-02

In [16]:
x = lfs2.iloc[0:2,:]
print(x)
lfs3 = pd.concat([lfs2,x],ignore_index=True)
lfs3

  ref_date  emplMale  emplPartBothSex  emplPartFemale
0  1976-01    6085.3              NaN           832.4
1  1976-02    6097.0              NaN           827.4

    ref_date  emplMale  emplPartBothSex  emplPartFemale
0    1976-01    6085.3              NaN           832.4
1    1976-02    6097.0              NaN           827.4
2    1976-03    6119.3              NaN           833.9
3    1976-04    6145.3              NaN           840.4
4    1976-05    6125.8              NaN           841.0
..       ...       ...              ...             ...
597  2025-10   11125.2           3844.4          2366.1
598  2025-11   11163.0           3907.4          2374.3
599  2025-12   11172.5           3865.4          2387.3
600  1976-01    6085.3              NaN           832.4
601  1976-02    6097.0              NaN           827.4

[602 rows x 4 columns]

In [17]:
lfs3.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
597    False
598    False
599    False
600     True
601     True
Length: 602, dtype: bool

In [18]:
lfs3=lfs3.drop_duplicates()

In [19]:
lfs3

    ref_date  emplMale  emplPartBothSex  emplPartFemale
0    1976-01    6085.3              NaN           832.4
1    1976-02    6097.0              NaN           827.4
2    1976-03    6119.3              NaN           833.9
3    1976-04    6145.3              NaN           840.4
4    1976-05    6125.8              NaN           841.0
..       ...       ...              ...             ...
595  2025-08   11052.8           3804.9          2351.8
596  2025-09   11103.6           3759.3          2348.0
597  2025-10   11125.2           3844.4          2366.1
598  2025-11   11163.0           3907.4          2374.3
599  2025-12   11172.5           3865.4          2387.3

[600 rows x 4 columns]

### Transforming Data Using a Function or Mapping
The `map` method is an iterable built-in function of Python. It iterates without needing to use `for` ... `in`.

The map method accepts a function or dictionary-like object containing a mapping to do the transformation of values:

In [20]:
# create a new column based on column emplPartFemale
x = {832.4:-2, 833.9:-1}
lfs3['emplPartF'] = lfs3['emplPartFemale'].map(x)
lfs3

    ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
0    1976-01    6085.3              NaN           832.4       -2.0
1    1976-02    6097.0              NaN           827.4        NaN
2    1976-03    6119.3              NaN           833.9       -1.0
3    1976-04    6145.3              NaN           840.4        NaN
4    1976-05    6125.8              NaN           841.0        NaN
..       ...       ...              ...             ...        ...
595  2025-08   11052.8           3804.9          2351.8        NaN
596  2025-09   11103.6           3759.3          2348.0        NaN
597  2025-10   11125.2           3844.4          2366.1        NaN
598  2025-11   11163.0           3907.4          2374.3        NaN
599  2025-12   11172.5           3865.4          2387.3        NaN

[600 rows x 5 columns]

The `map` method also accepts functions. We skip it.

### Replacing values
Use the `replace` method.

In [21]:
# replace all NaN to 100, and replace 2297.7 to -2297.7, wherever they are
lfs3.replace([np.nan, 2297.7], [100, -2297.7])

    ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
0    1976-01    6085.3            100.0           832.4       -2.0
1    1976-02    6097.0            100.0           827.4      100.0
2    1976-03    6119.3            100.0           833.9       -1.0
3    1976-04    6145.3            100.0           840.4      100.0
4    1976-05    6125.8            100.0           841.0      100.0
..       ...       ...              ...             ...        ...
595  2025-08   11052.8           3804.9          2351.8      100.0
596  2025-09   11103.6           3759.3          2348.0      100.0
597  2025-10   11125.2           3844.4          2366.1      100.0
598  2025-11   11163.0           3907.4          2374.3      100.0
599  2025-12   11172.5           3865.4          2387.3      100.0

[600 rows x 5 columns]

Again, the above creates a new object (without a variable name pointing to it). Ojbect lfs3 is not changed.

In [22]:
lfs3

    ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
0    1976-01    6085.3              NaN           832.4       -2.0
1    1976-02    6097.0              NaN           827.4        NaN
2    1976-03    6119.3              NaN           833.9       -1.0
3    1976-04    6145.3              NaN           840.4        NaN
4    1976-05    6125.8              NaN           841.0        NaN
..       ...       ...              ...             ...        ...
595  2025-08   11052.8           3804.9          2351.8        NaN
596  2025-09   11103.6           3759.3          2348.0        NaN
597  2025-10   11125.2           3844.4          2366.1        NaN
598  2025-11   11163.0           3907.4          2374.3        NaN
599  2025-12   11172.5           3865.4          2387.3        NaN

[600 rows x 5 columns]

To change apply the changes to lfs3, use `inplace=True`.

In [23]:
lfs3.replace([np.nan, 2297.7], [100, -2297.7], inplace=True)

In [24]:
lfs3

    ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
0    1976-01    6085.3            100.0           832.4       -2.0
1    1976-02    6097.0            100.0           827.4      100.0
2    1976-03    6119.3            100.0           833.9       -1.0
3    1976-04    6145.3            100.0           840.4      100.0
4    1976-05    6125.8            100.0           841.0      100.0
..       ...       ...              ...             ...        ...
595  2025-08   11052.8           3804.9          2351.8      100.0
596  2025-09   11103.6           3759.3          2348.0      100.0
597  2025-10   11125.2           3844.4          2366.1      100.0
598  2025-11   11163.0           3907.4          2374.3      100.0
599  2025-12   11172.5           3865.4          2387.3      100.0

[600 rows x 5 columns]

To replace values in a particular column:

In [25]:
lfs3['emplMale'].replace(10676.8,-5, inplace=True)
lfs3

    ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
0    1976-01    6085.3            100.0           832.4       -2.0
1    1976-02    6097.0            100.0           827.4      100.0
2    1976-03    6119.3            100.0           833.9       -1.0
3    1976-04    6145.3            100.0           840.4      100.0
4    1976-05    6125.8            100.0           841.0      100.0
..       ...       ...              ...             ...        ...
595  2025-08   11052.8           3804.9          2351.8      100.0
596  2025-09   11103.6           3759.3          2348.0      100.0
597  2025-10   11125.2           3844.4          2366.1      100.0
598  2025-11   11163.0           3907.4          2374.3      100.0
599  2025-12   11172.5           3865.4          2387.3      100.0

[600 rows x 5 columns]

### Setting index
We could have set index when reading the .csv file. We can set index.

In [26]:
lfs3.index = lfs3.ref_date
lfs3

         ref_date  emplMale  emplPartBothSex  emplPartFemale  emplPartF
ref_date
1976-01   1976-01    6085.3            100.0           832.4       -2.0
1976-02   1976-02    6097.0            100.0           827.4      100.0
1976-03   1976-03    6119.3            100.0           833.9       -1.0
1976-04   1976-04    6145.3            100.0           840.4      100.0
1976-05   1976-05    6125.8            100.0           841.0      100.0
...           ...       ...              ...             ...        ...
2025-08   2025-08   11052.8           3804.9          2351.8      100.0
2025-09   2025-09   11103.6           3759.3          2348.0      100.0
2025-10   2025-10   11125.2           3844.4          2366.1      100.0
2025-11   2025-11   11163.0           3907.4          2374.3      100.0
2025-12   2025-12   11172.5           3865.4          2387.3      100.0

[600 rows x 5 columns]

Alternatively, we can convert a column to be the index:

In [27]:
lfs3.set_index('ref_date', inplace=True)
lfs3

          emplMale  emplPartBothSex  emplPartFemale  emplPartF
ref_date
1976-01     6085.3            100.0           832.4       -2.0
1976-02     6097.0            100.0           827.4      100.0
1976-03     6119.3            100.0           833.9       -1.0
1976-04     6145.3            100.0           840.4      100.0
1976-05     6125.8            100.0           841.0      100.0
...            ...              ...             ...        ...
2025-08    11052.8           3804.9          2351.8      100.0
2025-09    11103.6           3759.3          2348.0      100.0
2025-10    11125.2           3844.4          2366.1      100.0
2025-11    11163.0           3907.4          2374.3      100.0
2025-12    11172.5           3865.4          2387.3      100.0

[600 rows x 4 columns]

### Outliers and data selection
Often, we want to remove outliers.

In [28]:
lfs3.describe()

           emplMale  emplPartBothSex  emplPartFemale   emplPartF
count    600.000000       600.000000      600.000000  600.000000
mean    8151.525667      2605.991667     1813.342167   99.661667
std     1375.427207       936.522600      435.665778    5.855283
min     6085.300000       100.000000      827.400000   -2.000000
25%     6986.975000      2118.675000     1504.275000  100.000000
50%     8009.350000      2688.100000     1864.050000  100.000000
75%     9277.600000      3359.750000     2220.200000  100.000000
max    11172.500000      3907.400000     2420.500000  100.000000

Suppose that negative vlaues are considered to be outliers, we can select rows with non-negative values of the entire data set or of a particular column.

In [29]:
# Select all rows where all columns are non-negative
lfs4= lfs3[(lfs3>=0).all(axis="columns")]
lfs4.describe()

           emplMale  emplPartBothSex  emplPartFemale  emplPartF
count    598.000000       598.000000      598.000000      598.0
mean    8158.379264      2614.372910     1816.620401      100.0
std     1372.596656       926.770729      432.678960        0.0
min     6097.000000       100.000000      827.400000      100.0
25%     6992.200000      2128.150000     1506.300000      100.0
50%     8014.250000      2692.350000     1868.450000      100.0
75%     9279.200000      3360.850000     2220.400000      100.0
max    11172.500000      3907.400000     2420.500000      100.0

In [30]:
# Select all rows where column emplMale is non-negative
lfs4= lfs3.loc[lfs3['emplMale']>=0,:]
lfs4

          emplMale  emplPartBothSex  emplPartFemale  emplPartF
ref_date
1976-01     6085.3            100.0           832.4       -2.0
1976-02     6097.0            100.0           827.4      100.0
1976-03     6119.3            100.0           833.9       -1.0
1976-04     6145.3            100.0           840.4      100.0
1976-05     6125.8            100.0           841.0      100.0
...            ...              ...             ...        ...
2025-08    11052.8           3804.9          2351.8      100.0
2025-09    11103.6           3759.3          2348.0      100.0
2025-10    11125.2           3844.4          2366.1      100.0
2025-11    11163.0           3907.4          2374.3      100.0
2025-12    11172.5           3865.4          2387.3      100.0

[600 rows x 4 columns]

In [31]:
lfs5 = lfs3.loc[lfs3['emplPartBothSex']>100,:]
lfs5

          emplMale  emplPartBothSex  emplPartFemale  emplPartF
ref_date
1979-09     6577.5           1509.7          1059.6      100.0
1979-10     6587.9           1512.4          1075.6      100.0
1979-11     6602.0           1518.5          1079.1      100.0
1979-12     6608.9           1519.1          1074.6      100.0
1980-01     6609.8           1522.1          1087.5      100.0
...            ...              ...             ...        ...
2025-08    11052.8           3804.9          2351.8      100.0
2025-09    11103.6           3759.3          2348.0      100.0
2025-10    11125.2           3844.4          2366.1      100.0
2025-11    11163.0           3907.4          2374.3      100.0
2025-12    11172.5           3865.4          2387.3      100.0

[556 rows x 4 columns]

We can set the outliers to specific values. For example, where appropriate, we can set negative values to zeros:

In [32]:
lfs3[lfs3<0.0] = 0.0
lfs3

          emplMale  emplPartBothSex  emplPartFemale  emplPartF
ref_date
1976-01     6085.3            100.0           832.4        0.0
1976-02     6097.0            100.0           827.4      100.0
1976-03     6119.3            100.0           833.9        0.0
1976-04     6145.3            100.0           840.4      100.0
1976-05     6125.8            100.0           841.0      100.0
...            ...              ...             ...        ...
2025-08    11052.8           3804.9          2351.8      100.0
2025-09    11103.6           3759.3          2348.0      100.0
2025-10    11125.2           3844.4          2366.1      100.0
2025-11    11163.0           3907.4          2374.3      100.0
2025-12    11172.5           3865.4          2387.3      100.0

[600 rows x 4 columns]

### Creating dummy variables
Dummy variables take values of 1 and 0. 

We can convert a categorical variable into a dummy matrix. For example, if a column in a DataFrame has 3 distinct values, we would derive a matrix or DataFrame with 3 columns containing 1s and 0s. This is done by function `get_dummies`.

We read in another data, create sex dummy variables, and merge them to main data.

In [33]:
cansimid = '14100287'
filename = 'tbl14100287_bySex.csv'
#lfs = pd.read_csv(filename, index_col=[0,1])
lfs_bySex = pd.read_csv(filename,index_col=0)
lfs_bySex.head()

,gender,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
ref_date,,,,,,,,,,
1976-01,Men+,6085.3,5712.1,373.2,73.0,6504.3,78.0,8334.7,419.0,6.4
1976-01,Total - Gender,9636.7,8431.0,1205.6,57.2,10369.7,61.5,16852.4,733.0,7.1
1976-01,Women+,3551.3,2718.9,832.4,41.7,3865.4,45.4,8517.7,314.0,8.1
1976-02,Men+,6097.0,5732.0,364.9,73.0,6513.1,78.0,8353.3,416.2,6.4
1976-02,Total - Gender,9659.8,8467.5,1192.3,57.2,10389.8,61.5,16892.0,730.0,7.0

In [34]:
dummies = pd.get_dummies(lfs_bySex["gender"], prefix="d_", dtype=float)
lfs_bySexDummy = lfs_bySex.join(dummies)
lfs_bySexDummy

,gender,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate,d__Men+,d__Total - Gender,d__Women+
ref_date,,,,,,,,,,,,,
1976-01,Men+,6085.3,5712.1,373.2,73.0,6504.3,78.0,8334.7,419.0,6.4,1.0,0.0,0.0
1976-01,Men+,6085.3,5712.1,373.2,73.0,6504.3,78.0,8334.7,419.0,6.4,0.0,1.0,0.0
1976-01,Men+,6085.3,5712.1,373.2,73.0,6504.3,78.0,8334.7,419.0,6.4,0.0,0.0,1.0
1976-01,Total - Gender,9636.7,8431.0,1205.6,57.2,10369.7,61.5,16852.4,733.0,7.1,1.0,0.0,0.0
1976-01,Total - Gender,9636.7,8431.0,1205.6,57.2,10369.7,61.5,16852.4,733.0,7.1,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12,Total - Gender,20917.4,17150.7,3766.6,61.0,22422.8,65.4,34285.1,1505.5,6.7,0.0,1.0,0.0
2024-12,Total - Gender,20917.4,17150.7,3766.6,61.0,22422.8,65.4,34285.1,1505.5,6.7,0.0,0.0,1.0
2024-12,Women+,9858.0,7504.7,2353.3,57.2,10536.6,61.1,17231.5,678.5,6.4,1.0,0.0,0.0
2024-12,Women+,9858.0,7504.7,2353.3,57.2,10536.6,61.1,17231.5,678.5,6.4,0.0,1.0,0.0
2024-12,Women+,9858.0,7504.7,2353.3,57.2,10536.6,61.1,17231.5,678.5,6.4,0.0,0.0,1.0

### Data selection in data with multindex
A data set can have more than one index.

Setting multi-indexes: both time and sex are set as index

In [35]:
cansimid = '14100287'
filename = 'tbl14100287_bySex.csv'
lfs_bySex = pd.read_csv(filename)
lfs_bySex = lfs_bySex.set_index(['ref_date','gender'])
# The line above is unnecessary if we set data when reading it: 
# lfs_bySex = pd.read_csv(filename, index_col=[0,1])
lfs_bySex.index

MultiIndex([('1976-01',           'Men+'),
            ('1976-01', 'Total - Gender'),
            ('1976-01',         'Women+'),
            ('1976-02',           'Men+'),
            ('1976-02', 'Total - Gender'),
            ('1976-02',         'Women+'),
            ('1976-03',           'Men+'),
            ('1976-03', 'Total - Gender'),
            ('1976-03',         'Women+'),
            ('1976-04',           'Men+'),
            ...
            ('2024-09',         'Women+'),
            ('2024-10',           'Men+'),
            ('2024-10', 'Total - Gender'),
            ('2024-10',         'Women+'),
            ('2024-11',           'Men+'),
            ('2024-11', 'Total - Gender'),
            ('2024-11',         'Women+'),
            ('2024-12',           'Men+'),
            ('2024-12', 'Total - Gender'),
            ('2024-12',         'Women+')],
           names=['ref_date', 'gender'], length=1764)

Data selection by multi-index

In [36]:
lfs5 = lfs_bySex.loc[[('2023-11','Men+'), ('2023-12','Men+')]]
lfs5

,,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
ref_date,gender,,,,,,,,,
2023-11,Men+,10819.4,9403.9,1415.6,65.9,11506.3,70.1,16411.0,686.9,6.0
2023-12,Men+,10829.5,9439.2,1390.3,65.8,11519.7,70.0,16460.1,690.2,6.0

Summary statistics by index:

In [37]:
lfs_bySex.groupby(level="gender").sum()

,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
gender,,,,,,,,,
Men+,4757669.3,4245982.7,511687.5,39659.6,5178087.1,43227.7,7089752.7,420418.3,4843.6
Total - Gender,8732761.8,7161617.1,1571147.3,35538.8,9478548.4,38648.2,14396736.0,745784.5,4735.8
Women+,3975094.7,2915635.4,1059461.1,31541.0,4300460.0,34207.3,7306983.4,325367.8,4630.9

In [38]:
lfs_bySex.groupby(level=0).mean()

,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
ref_date,,,,,,,,,
1976-01,6424.433333,5620.666667,803.733333,57.300000,6913.133333,61.633333,11234.933333,488.666667,7.200000
1976-02,6439.866667,5644.966667,794.866667,57.300000,6926.500000,61.633333,11261.366667,486.666667,7.166667
1976-03,6469.466667,5672.966667,796.500000,57.433333,6930.466667,61.500000,11287.133333,461.000000,6.800000
1976-04,6492.133333,5693.366667,798.700000,57.500000,6967.533333,61.700000,11312.933333,475.400000,6.966667
1976-05,6484.066667,5686.433333,797.600000,57.333333,6964.033333,61.533333,11338.733333,480.000000,7.066667
...,...,...,...,...,...,...,...,...,...
2024-08,13828.400000,11293.400000,2535.000000,61.033333,14813.933333,65.366667,22663.433333,985.533333,6.633333
2024-09,13852.866667,11354.700000,2498.133333,61.000000,14825.066667,65.233333,22726.533333,972.200000,6.566667
2024-10,13855.066667,11359.133333,2495.966667,60.833333,14839.300000,65.166667,22775.800000,984.200000,6.600000
2024-11,13884.266667,11394.400000,2489.866667,60.866667,14911.366667,65.400000,22816.800000,1027.066667,6.900000
2024-12,13944.900000,11433.800000,2511.066667,61.033333,14948.566667,65.400000,22856.700000,1003.666667,6.700000

Selection by groupby:

In [39]:
grouped = lfs_bySex.groupby(level="gender")
lfs5 = grouped.get_group("Men+")
lfs5

,,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
ref_date,gender,,,,,,,,,
1976-01,Men+,6085.3,5712.1,373.2,73.0,6504.3,78.0,8334.7,419.0,6.4
1976-02,Men+,6097.0,5732.0,364.9,73.0,6513.1,78.0,8353.3,416.2,6.4
1976-03,Men+,6119.3,5758.5,360.8,73.1,6515.3,77.8,8371.6,396.0,6.1
1976-04,Men+,6145.3,5787.6,357.6,73.2,6547.3,78.0,8390.0,402.0,6.1
1976-05,Men+,6125.8,5770.4,355.4,72.9,6528.0,77.6,8408.4,402.2,6.2
...,...,...,...,...,...,...,...,...,...,...
2024-08,Men+,10932.8,9500.8,1432.0,64.7,11773.1,69.6,16904.5,840.3,7.1
2024-09,Men+,10950.4,9531.9,1418.5,64.6,11785.6,69.5,16953.2,835.2,7.1
2024-10,Men+,10964.1,9548.7,1415.5,64.5,11798.9,69.4,16991.4,834.8,7.1
2024-11,Men+,10998.7,9595.2,1403.5,64.6,11859.5,69.7,17023.0,860.8,7.3
2024-12,Men+,11059.3,9646.0,1413.3,64.9,11886.3,69.7,17053.5,827.0,7.0

## Combining data sets
We have used methods `join` and `concat` to merge data.

Three main methods:
- concat(): Merge multiple DataFrame objects along a shared index or column.
- merge(): Combine two DataFrame objects with SQL-style joining.
- append(): Add rows to DataFrame.

Due to time constraint, we only show examples when processing data.

For details, see pandas user guide: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#

## Reshaping and pivoting

Due to time constraint, we will use an example later on.

For details, see pandas user guide: https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html

## Aggregation and grouping
Aggregation refers to any data transformation that produces scalar values from arrays.

For example, calculating summary statistics from data is an aggregation.

Often aggregation is through `GroupBy` objects. In the above, we have calculate the total value of each variable (column) by sex, and the mean value of each column by date.

We will also skip this part.

## Time series data

This is another whole set of methods processing time series data.

I only show an example: set the LFS labor condition data to be time series, and convert monthly data to quarterly.

In [40]:
# Convert the index to time series
import datetime
cansimid = '14100287'
filename = 'tbl14100287_bySex.csv'
lfs_bySex = pd.read_csv(filename,index_col=0)
lfs_bySex.index=pd.to_datetime(lfs_bySex.index)
# Convert monthly data to quarterly
lfsQtr = lfs_bySex.groupby('gender').resample('QS-OCT').mean()
lfsQtr = lfsQtr.round(2)
lfsQtr

                      empl  emplFull  emplPart  emplRate  labForce  \
gender ref_date
Men+   1976-01-01  6100.53   5734.20    366.30     73.03   6510.90
       1976-04-01  6132.60   5772.83    359.73     72.93   6538.50
       1976-07-01  6143.37   5783.70    359.67     72.60   6560.70
       1976-10-01  6150.80   5777.90    372.87     72.30   6598.27
       1977-01-01  6169.17   5794.50    374.67     72.17   6640.27
...                    ...       ...       ...       ...       ...
Women+ 2023-10-01  9697.53   7420.63   2276.93     58.20  10260.60
       2024-01-01  9732.50   7431.70   2300.77     57.93  10312.50
       2024-04-01  9777.27   7413.17   2364.13     57.70  10403.90
       2024-07-01  9809.23   7463.17   2346.03     57.40  10439.97
       2024-10-01  9834.73   7497.03   2337.70     57.17  10501.40

                   participRate  population  unempl  unemplRate
gender ref_date
Men+   1976-01-01         77.93     8353.20  410.40        6.30
       1976-04-01         77.73     8408.40  405.90        6.20
       1976-07-01         77.53     8462.33  417.33        6.37
       1976-10-01         77.53     8505.33  447.50        6.77
       1977-01-01         77.70     8548.00  471.10        7.10
...                         ...         ...     ...         ...
Women+ 2023-10-01         61.53    16666.93  563.10        5.47
       2024-01-01         61.33    16803.07  580.00        5.63
       2024-04-01         61.40    16946.37  626.60        6.03
       2024-07-01         61.07    17091.23  630.73        6.07
       2024-10-01         61.03    17202.00  666.60        6.33

[588 rows x 9 columns]

In [41]:
lfsQtr.loc['Men+',:]

,empl,emplFull,emplPart,emplRate,labForce,participRate,population,unempl,unemplRate
ref_date,,,,,,,,,
1976-01-01,6100.53,5734.20,366.30,73.03,6510.90,77.93,8353.20,410.40,6.30
1976-04-01,6132.60,5772.83,359.73,72.93,6538.50,77.73,8408.40,405.90,6.20
1976-07-01,6143.37,5783.70,359.67,72.60,6560.70,77.53,8462.33,417.33,6.37
1976-10-01,6150.80,5777.90,372.87,72.30,6598.27,77.53,8505.33,447.50,6.77
1977-01-01,6169.17,5794.50,374.67,72.17,6640.27,77.70,8548.00,471.10,7.10
...,...,...,...,...,...,...,...,...,...
2023-10-01,10817.57,9416.27,1401.33,65.90,11504.57,70.10,16411.03,687.03,6.00
2024-01-01,10867.27,9448.40,1418.90,65.57,11577.10,69.83,16570.10,709.83,6.13
2024-04-01,10927.63,9514.40,1413.23,65.27,11690.30,69.83,16737.87,762.67,6.53
2024-07-01,10935.70,9520.23,1415.47,64.70,11758.93,69.53,16903.70,823.23,7.00
2024-10-01,11007.37,9596.63,1410.77,64.67,11848.23,69.60,17022.63,840.87,7.13